### PR TITLE
Linear Search

### PR DESCRIPTION
**Pull request by PIYUSH-MISHRA-00**
## Issue Number
- 31
## Issue Description
- Java Program for Linear Search 
## Proposed Change
- Written a simple program for Linear Search in Java
## Additional Info (Optional)
- Added explanation in comments
## Checklist
- [x] Testing
- [x] Documentations
- [x] I have read the [CONTRIBUTING](../Contributing.md) guidelines
- [x] Added explanation of the Code in a README file

### CODE REVIEW

**Comment by PIYUSH-MISHRA-00** [comment]
Linear Search program is done.

**Comment by abirbhattacharya82** [comment]
@PIYUSH-MISHRA-00 could you just a README.md inside Linear Search Folder explaining how the algo works???

**Comment by abirbhattacharya82** [comment]
Just copy the comments and put it inside the README.md file.

**Comment by PIYUSH-MISHRA-00** [comment]
added a Readme.md file in the Linear Search folder

**Comment by abirbhattacharya82** [comment]
LGTM 👍🏽 
Thanks for the contribution ❤️ 
Leave a ⭐ if you liked the repo

**Pull request merged**
