### PR TITLE
added quick sort

### PR DESCRIPTION
**Pull request by Niravprajapati1**
## Issue Number
#8 
## Issue Description
- add quick sort algorithm
## Proposed Change
- added quick sort algorithm 
## Additional Info (Optional)
- Any Additional Information
## Checklist
- [x] Testing
- [x] Documentations
- [x] I have read the [CONTRIBUTING](../Contributing.md) guidelines

### CODE REVIEW

**Comment by abirbhattacharya82** [comment]
Hi, @Niravprajapati1, could you add a readme file in the same folder describing how the program works? It will be great for people looking for the code to understand clearly.
Thanks 👍🏽

**Comment by Niravprajapati1** [comment]
Sure. Can i use photos for readme file ?

**Comment by abirbhattacharya82** [comment]
Yes you can use them. Just make sure that you don't include those pics in this repository

**Comment by Niravprajapati1** [comment]
✅

**Comment by abirbhattacharya82** [comment]
LGTM 🚀 
thanks for the contribution 👍🏽

**Pull request merged**
